language: php

php:
  - 5.5

sudo: false

cache:
  directories:
    - ~/.composer/cache

install:
  - if [[ $TRAVIS_BRANCH = master ]]; then export COMPOSER_ROOT_VERSION=dev-master; else export COMPOSER_ROOT_VERSION=$TRAVIS_BRANCH.x-dev; fi;
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: d2a43e8a8a584e1c9e6d8e2ec1f3bd1052a67bc5879431d2a3ac1c5304dfb954

after_script:
  - ./bin/test-reporter
