parameters:
    open_orchestra_media_file.manager.storage.class: OpenOrchestra\MediaFileBundle\Manager\MediaStorageManager

services:
    open_orchestra_media_file.manager.storage:
        class: %open_orchestra_media_file.manager.storage.class%
        arguments:
            - @knp_gaufrette.filesystem_map
            - %open_orchestra_media.filesystem%
